on: push

jobs:
  my-job:
    name: deploy1
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          sftp_only: no
          server: '3.110.197.118'
          port: 22
          username: ${{ secrets.NODEUSER }}
          password: ${{ secrets.NODEPASSWORD }}
          #username: ${{ secrets.FRONTENDUSER }}
          local_path: './*'
          remote_path: '/var/www/html/backend'
          exclude: '["node_modules/**", "_secret.php", ".github/**", ".git/**", "*.env"]'
          pasive: true
